name: uumevents
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.0.0
  provider: ^6.0.5
  intl: ^0.18.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  flutter_svg: ^2.0.7
  flutter_keyboard_visibility: ^5.4.1
  google_fonts: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - assets/images/
    - assets/icons/